FROM node:22-alpine
WORKDIR /app
ARG DB_URL 
ENV DATABASE_URL=${DB_URL}

COPY package*.json ./
COPY turbo.json ./
COPY packages ./packages
COPY apps/ws-server ./apps/ws-server

RUN npm i 
RUN npm run build:packages
RUN npm run db:generate
EXPOSE 8001

CMD ["npm","run","start:ws-server"]





