FROM node:22-alpine

WORKDIR /app
ARG DB_URL 
ENV DATABASE_URL=${DB_URL}

COPY package*.json ./
COPY turbo.json ./
COPY packages ./packages
COPY apps/http-server ./apps/http-server

RUN npm i 

RUN npm run build:packages

EXPOSE 8000

CMD ["npm","run","start:backend"]

